### ISSUE TITLE
Structure source

### ISSUE THREAD

**Issue by renatobenks-zz** [marlon407/flask-rest#1]
Eai marlon, tem alguma ideia massa pra estruturar o código de uma api rest com Flask? 😂 

Não achei nenhuma convenção por default usado pra estruturar. Se tu tiver alguma forma ou padrão, manda a ideia [aqui](https://github.com/renatobenks/example-api/issues). 👊 
##

**Comment by marlon407** [comment]
Eu tentei procurar alguma coisa tb e não achei nada!! O Ciro chegou a
montar uma estrutura massa, mas nada que foge muito do Models/Views do
DjangoRestFramework!
